// Service-area data for /areas-we-serve. Each entry: [name, cities, notable industries].
// EdgeWeb is Delhi-based and delivers remote-first; these are markets served,
// not office locations — copy on the page must never imply local offices.

export const INDIA_STATES = [
  ['Andhra Pradesh', 'Visakhapatnam, Vijayawada, Guntur, Tirupati', 'pharma, aquaculture, IT'],
  ['Arunachal Pradesh', 'Itanagar, Naharlagun', 'tourism, hydropower, handicrafts'],
  ['Assam', 'Guwahati, Dibrugarh, Silchar', 'tea, oil and gas, tourism'],
  ['Bihar', 'Patna, Gaya, Muzaffarpur', 'agri-processing, education, retail'],
  ['Chhattisgarh', 'Raipur, Bhilai, Bilaspur', 'steel, mining, power'],
  ['Goa', 'Panaji, Margao, Vasco da Gama', 'tourism, hospitality, pharma'],
  ['Gujarat', 'Ahmedabad, Surat, Vadodara, Rajkot', 'textiles, diamonds, chemicals, manufacturing'],
  ['Haryana', 'Gurugram, Faridabad, Panipat, Ambala', 'IT services, automotive, textiles'],
  ['Himachal Pradesh', 'Shimla, Dharamshala, Solan', 'tourism, horticulture, pharma'],
  ['Jharkhand', 'Ranchi, Jamshedpur, Dhanbad', 'steel, mining, engineering'],
  ['Karnataka', 'Bengaluru, Mysuru, Mangaluru, Hubballi', 'IT, startups, aerospace, biotech'],
  ['Kerala', 'Kochi, Thiruvananthapuram, Kozhikode', 'tourism, healthcare, spices, IT'],
  ['Madhya Pradesh', 'Indore, Bhopal, Jabalpur, Gwalior', 'agriculture, manufacturing, retail'],
  ['Maharashtra', 'Mumbai, Pune, Nagpur, Nashik', 'finance, IT, manufacturing, media'],
  ['Manipur', 'Imphal', 'handicrafts, agriculture, tourism'],
  ['Meghalaya', 'Shillong', 'tourism, mining, agriculture'],
  ['Mizoram', 'Aizawl', 'agriculture, handicrafts, tourism'],
  ['Nagaland', 'Kohima, Dimapur', 'handicrafts, agriculture, tourism'],
  ['Odisha', 'Bhubaneswar, Cuttack, Rourkela', 'steel, mining, IT'],
  ['Punjab', 'Ludhiana, Amritsar, Jalandhar, Mohali', 'manufacturing, agriculture, textiles'],
  ['Rajasthan', 'Jaipur, Jodhpur, Udaipur, Kota', 'tourism, handicrafts, education'],
  ['Sikkim', 'Gangtok', 'tourism, organic farming, hydropower'],
  ['Tamil Nadu', 'Chennai, Coimbatore, Madurai, Tiruchirappalli', 'manufacturing, automotive, textiles, IT'],
  ['Telangana', 'Hyderabad, Warangal', 'IT, pharma, biotech'],
  ['Tripura', 'Agartala', 'agriculture, handicrafts, tourism'],
  ['Uttar Pradesh', 'Noida, Lucknow, Kanpur, Agra, Varanasi, Ghaziabad', 'manufacturing, leather, retail, IT'],
  ['Uttarakhand', 'Dehradun, Haridwar, Haldwani', 'tourism, pharma, wellness'],
  ['West Bengal', 'Kolkata, Siliguri, Durgapur', 'jute, retail, IT, education'],
];

export const INDIA_UTS = [
  ['Delhi (NCT)', 'New Delhi, Dwarka, Rohini, Saket', 'retail, services, startups'],
  ['Chandigarh', 'Chandigarh', 'IT, education, services'],
  ['Puducherry', 'Puducherry, Karaikal', 'tourism, manufacturing, education'],
  ['Jammu and Kashmir', 'Srinagar, Jammu', 'handicrafts, horticulture, tourism'],
  ['Ladakh', 'Leh, Kargil', 'tourism, handicrafts'],
  ['Andaman and Nicobar Islands', 'Port Blair', 'tourism, fisheries'],
  ['Lakshadweep', 'Kavaratti', 'fisheries, tourism'],
  ['Dadra and Nagar Haveli and Daman and Diu', 'Silvassa, Daman', 'manufacturing, pharma'],
];

export const USA_STATES = [
  ['Alabama', 'Birmingham, Huntsville, Montgomery', 'aerospace, automotive, healthcare'],
  ['Alaska', 'Anchorage, Fairbanks', 'energy, fishing, tourism'],
  ['Arizona', 'Phoenix, Tucson, Scottsdale', 'semiconductors, real estate, tourism'],
  ['Arkansas', 'Little Rock, Fayetteville', 'retail, logistics, agriculture'],
  ['California', 'Los Angeles, San Francisco, San Diego, San Jose', 'technology, entertainment, agriculture'],
  ['Colorado', 'Denver, Boulder, Colorado Springs', 'aerospace, outdoor, technology'],
  ['Connecticut', 'Hartford, Stamford, New Haven', 'insurance, finance, manufacturing'],
  ['Delaware', 'Wilmington, Dover', 'finance, corporate services, chemicals'],
  ['Florida', 'Miami, Orlando, Tampa, Jacksonville', 'tourism, real estate, healthcare'],
  ['Georgia', 'Atlanta, Savannah, Augusta', 'logistics, media, fintech'],
  ['Hawaii', 'Honolulu', 'tourism, hospitality'],
  ['Idaho', 'Boise, Meridian', 'technology, agriculture'],
  ['Illinois', 'Chicago, Naperville, Springfield', 'finance, logistics, manufacturing'],
  ['Indiana', 'Indianapolis, Fort Wayne', 'manufacturing, life sciences'],
  ['Iowa', 'Des Moines, Cedar Rapids', 'agriculture, insurance'],
  ['Kansas', 'Wichita, Overland Park, Kansas City', 'aviation, agriculture'],
  ['Kentucky', 'Louisville, Lexington', 'logistics, automotive, healthcare'],
  ['Louisiana', 'New Orleans, Baton Rouge', 'energy, tourism, shipping'],
  ['Maine', 'Portland, Bangor', 'tourism, fisheries'],
  ['Maryland', 'Baltimore, Bethesda, Rockville', 'biotech, government contracting'],
  ['Massachusetts', 'Boston, Cambridge, Worcester', 'biotech, education, technology'],
  ['Michigan', 'Detroit, Grand Rapids, Ann Arbor', 'automotive, manufacturing'],
  ['Minnesota', 'Minneapolis, Saint Paul, Rochester', 'healthcare, retail, manufacturing'],
  ['Mississippi', 'Jackson, Gulfport', 'agriculture, manufacturing'],
  ['Missouri', 'Kansas City, Saint Louis', 'logistics, healthcare, manufacturing'],
  ['Montana', 'Billings, Missoula', 'agriculture, tourism'],
  ['Nebraska', 'Omaha, Lincoln', 'agriculture, insurance'],
  ['Nevada', 'Las Vegas, Reno', 'hospitality, gaming, logistics'],
  ['New Hampshire', 'Manchester, Nashua', 'manufacturing, technology'],
  ['New Jersey', 'Newark, Jersey City, Princeton', 'pharma, logistics, finance'],
  ['New Mexico', 'Albuquerque, Santa Fe', 'aerospace, energy, tourism'],
  ['New York', 'New York City, Buffalo, Albany', 'finance, media, retail'],
  ['North Carolina', 'Charlotte, Raleigh, Durham', 'banking, biotech, technology'],
  ['North Dakota', 'Fargo, Bismarck', 'energy, agriculture'],
  ['Ohio', 'Columbus, Cleveland, Cincinnati', 'manufacturing, healthcare, insurance'],
  ['Oklahoma', 'Oklahoma City, Tulsa', 'energy, aerospace'],
  ['Oregon', 'Portland, Eugene, Salem', 'technology, apparel, outdoor'],
  ['Pennsylvania', 'Philadelphia, Pittsburgh, Harrisburg', 'healthcare, education, manufacturing'],
  ['Rhode Island', 'Providence, Warwick', 'healthcare, manufacturing'],
  ['South Carolina', 'Charleston, Columbia, Greenville', 'automotive, tourism, manufacturing'],
  ['South Dakota', 'Sioux Falls, Rapid City', 'finance, agriculture'],
  ['Tennessee', 'Nashville, Memphis, Knoxville', 'healthcare, music, logistics'],
  ['Texas', 'Houston, Dallas, Austin, San Antonio', 'energy, technology, healthcare'],
  ['Utah', 'Salt Lake City, Provo, Lehi', 'technology, software, outdoor'],
  ['Vermont', 'Burlington, Montpelier', 'agriculture, tourism'],
  ['Virginia', 'Richmond, Arlington, Virginia Beach', 'government contracting, technology'],
  ['Washington', 'Seattle, Bellevue, Spokane', 'cloud, aerospace, retail'],
  ['West Virginia', 'Charleston, Morgantown', 'energy, healthcare'],
  ['Wisconsin', 'Milwaukee, Madison, Green Bay', 'manufacturing, dairy, healthcare'],
  ['Wyoming', 'Cheyenne, Casper', 'energy, tourism'],
];

export const EUROPE_COUNTRIES = [
  ['United Kingdom', 'London, Manchester, Birmingham, Edinburgh', 'fintech, retail, creative industries'],
  ['Ireland', 'Dublin, Cork, Galway', 'technology, pharma, financial services'],
  ['Germany', 'Berlin, Munich, Hamburg, Frankfurt', 'manufacturing, automotive, engineering'],
  ['France', 'Paris, Lyon, Marseille', 'luxury, retail, aerospace'],
  ['Netherlands', 'Amsterdam, Rotterdam, Utrecht', 'logistics, e-commerce, fintech'],
  ['Belgium', 'Brussels, Antwerp', 'logistics, pharma, professional services'],
  ['Spain', 'Madrid, Barcelona, Valencia', 'tourism, retail, startups'],
  ['Portugal', 'Lisbon, Porto', 'tourism, startups, services'],
  ['Italy', 'Milan, Rome, Turin', 'fashion, manufacturing, design'],
  ['Switzerland', 'Zurich, Geneva, Basel', 'finance, pharma, precision engineering'],
  ['Austria', 'Vienna, Graz', 'manufacturing, tourism, finance'],
  ['Sweden', 'Stockholm, Gothenburg, Malmo', 'technology, gaming, fintech'],
  ['Norway', 'Oslo, Bergen', 'energy, shipping, technology'],
  ['Denmark', 'Copenhagen, Aarhus', 'design, renewable energy, life sciences'],
  ['Finland', 'Helsinki, Espoo, Tampere', 'technology, gaming, cleantech'],
  ['Poland', 'Warsaw, Krakow, Wroclaw', 'software, manufacturing, shared services'],
  ['Czech Republic', 'Prague, Brno', 'manufacturing, software, automotive'],
  ['Estonia', 'Tallinn, Tartu', 'digital services, startups, e-government'],
  ['Lithuania', 'Vilnius, Kaunas', 'fintech, technology, logistics'],
  ['Latvia', 'Riga', 'logistics, technology, services'],
  ['Greece', 'Athens, Thessaloniki', 'tourism, shipping, retail'],
  ['Romania', 'Bucharest, Cluj-Napoca', 'software, outsourcing, manufacturing'],
  ['Hungary', 'Budapest', 'manufacturing, software, services'],
  ['Luxembourg', 'Luxembourg City', 'banking, funds, professional services'],
];

export const AUSTRALIA_STATES = [
  ['New South Wales', 'Sydney, Newcastle, Wollongong', 'finance, professional services, retail'],
  ['Victoria', 'Melbourne, Geelong, Ballarat', 'education, healthcare, manufacturing'],
  ['Queensland', 'Brisbane, Gold Coast, Sunshine Coast', 'tourism, mining, construction'],
  ['Western Australia', 'Perth, Fremantle', 'mining, energy, agriculture'],
  ['South Australia', 'Adelaide', 'defence, wine, manufacturing'],
  ['Tasmania', 'Hobart, Launceston', 'tourism, agriculture, food'],
  ['Australian Capital Territory', 'Canberra', 'government, education, technology'],
  ['Northern Territory', 'Darwin, Alice Springs', 'mining, tourism, government'],
];

export const REGION_COUNTS = {
  india: INDIA_STATES.length + INDIA_UTS.length,
  usa: USA_STATES.length,
  europe: EUROPE_COUNTRIES.length,
  australia: AUSTRALIA_STATES.length,
};

export const slugify = (name) =>
  name.toLowerCase().replace(/&/g, 'and').replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
